### ISSUE TITLE
Danger has errored

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#1439]
> Would you mind making an issue, assigning it to me, and linking to the danger comment, please, so I can look into it later?

@hawkrives
https://github.com/StoDevX/AAO-React-Native/pull/1426#issuecomment-323221883
```
Danger has errored. Error: TypeError

TypeError: 'get' on proxy: property 'raw' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected '[object Array]' but got '[object Object]')
    at dedent (/home/travis/build/StoDevX/AAO-React-Native/node_modules/dedent/dist/dedent.js:10:18)
    at Object.apply (/home/travis/build/StoDevX/AAO-React-Native/node_modules/vm2/lib/contextify.js:288:34)
    at fileLog (/home/travis/build/StoDevX/AAO-React-Native/dangerfile.js:1:3062)
    at Object.<anonymous> (/home/travis/build/StoDevX/AAO-React-Native/dangerfile.js:1:3442)
    at NodeVM.run (/home/travis/build/StoDevX/AAO-React-Native/node_modules/vm2/lib/main.js:424:27)
    at Object.<anonymous> (/home/travis/build/StoDevX/AAO-React-Native/node_modules/danger/distribution/runner/DangerfileRunner.js:128:24)
    at step (/home/travis/build/StoDevX/AAO-React-Native/node_modules/danger/distribution/runner/DangerfileRunner.js:40:23)
    at Object.next (/home/travis/build/StoDevX/AAO-React-Native/node_modules/danger/distribution/runner/DangerfileRunner.js:21:53)
    at /home/travis/build/StoDevX/AAO-React-Native/node_modules/danger/distribution/runner/DangerfileRunner.js:15:71
    at Promise (<anonymous>)
```

**Comment by drewvolz** [comment]
@hawkrives is this still a concern?

**Comment by hawkrives** [comment]
Meh. No.
