### ISSUE TITLE
detox postinstall script failure

### ISSUE THREAD

**Issue by rye** [StoDevX/AAO-React-Native#2842]
```console
kristofer@maero ~/G/G/S/AAO-React-Native (master) [01] $ yarn
yarn install v1.9.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[----------------------------------------------------------------------] 0/1198(node:35430) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[3/4] 🔗  Linking dependencies...
warning " > react-native@0.55.4" has incorrect peer dependency "react@16.3.1".
warning "react-native > eslint-plugin-react-native@3.2.1" has incorrect peer dependency "eslint@^3.17.0 || ^4.0.0".
warning " > eslint-plugin-react-native@3.2.0" has incorrect peer dependency "eslint@^3.17.0 || ^4.0.0".
[4/4] 📃  Building fresh packages...
[4/5] ⠐ @mapbox/react-native-mapbox-gl
[-/5] ⠐ waiting...
[5/5] ⠐ detox
[-/5] ⠐ waiting...
error /Users/kristofer/Git/GitHub/StoDevX/AAO-React-Native/node_modules/detox: Command failed.
Exit code: 1
Command: node scripts/postinstall.js
Arguments:
Directory: /Users/kristofer/Git/GitHub/StoDevX/AAO-React-Native/node_modules/detox
Output:
+++ dirname /Users/kristofer/Git/GitHub/StoDevX/AAO-React-Native/node_modules/detox/scripts/build_framework.ios.sh
++ dirname /Users/kristofer/Git/GitHub/StoDevX/AAO-React-Native/node_modules/detox/scripts
+ detoxRootPath=/Users/kristofer/Git/GitHub/StoDevX/AAO-React-Native/node_modules/detox
++ node -p 'require('\''/Users/kristofer/Git/GitHub/StoDevX/AAO-React-Native/node_modules/detox/package.json'\'').version'
+ detoxVersion=8.1.6
++ echo 8.1.6
++ xcodebuild -version
++ shasum
++ awk '{print $1}'
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
+ sha1=aba5c8f25bf328b40be1e29d2d653101f6ecc89d
+ detoxFrameworkDirPath=/Users/kristofer/Library/Detox/ios/aba5c8f25bf328b40be1e29d2d653101f6ecc89d
+ detoxFrameworkPath=/Users/kristofer/Library/Detox/ios/aba5c8f25bf328b40be1e29d2d653101f6ecc89d/Detox.framework
+ main
+ '[' -d /Users/kristofer/Library/Detox/ios/aba5c8f25bf328b40be1e29d2d653101f6ecc89d ']'
+ '[' '!' -d /Users/kristofer/Library/Detox/ios/aba5c8f25bf328b40be1e29d2d653101f6ecc89d/Detox.framework ']'
+ echo '/Users/kristofer/Library/Detox/ios/aba5c8f25bf328b40be1e29d2d653101f6ecc89d was found, but could not find Detox.framework inside it. This means that the Detox framework build process was interrupted.
         deleting /Users/kristofer/Library/Detox/ios/aba5c8f25bf328b40be1e29d2d653101f6ecc89d and trying to rebuild.'
/Users/kristofer/Library/Detox/ios/aba5c8f25bf328b40be1e29d2d653101f6ecc89d was found, but could not find Detox.framework inside it. This means that the Detox framework build process was interrupted.
         deleting /Users/kristofer/Library/Detox/ios/aba5c8f25bf328b40be1e29d2d653101f6ecc89d and trying to rebuild.
+ rm -rf /Users/kristofer/Library/Detox/ios/aba5c8f25bf328b40be1e29d2d653101f6ecc89d
+ prepareAndBuildFramework
+ '[' -d /Users/kristofer/Git/GitHub/StoDevX/AAO-React-Native/node_modules/detox/ios ']'
+ detoxSourcePath=/Users/kristofer/Git/GitHub/StoDevX/AAO-React-Native/node_modules/detox/ios_src
+ extractSources /Users/kristofer/Git/GitHub/StoDevX/AAO-React-Native/node_modules/detox/ios_src
+ detoxSourcePath=/Users/kristofer/Git/GitHub/StoDevX/AAO-React-Native/node_modules/detox/ios_src
+ echo 'Extracting Detox sources...'
Extracting Detox sources...
+ mkdir -p /Users/kristofer/Git/GitHub/StoDevX/AAO-React-Native/node_modules/detox/ios_src
+ tar -xjf /Users/kristofer/Git/GitHub/StoDevX/AAO-React-Native/node_modules/detox/Detox-ios-src.tbz -C /Users/kristofer/Git/GitHub/StoDevX/AAO-React-Native/node_modules/detox/ios_src
+ buildFramework /Users/kristofer/Git/GitHub/StoDevX/AAO-React-Native/node_modules/detox/ios_src
+ detoxSourcePath=/Users/kristofer/Git/GitHub/StoDevX/AAO-React-Native/node_modules/detox/ios_src
+ echo 'Building Detox.framework from /Users/kristofer/Git/GitHub/StoDevX/AAO-React-Native/node_modules/detox/ios_src...'
+ mkdir -p /Users/kristofer/Library/Detox/ios/aba5c8f25bf328b40be1e29d2d653101f6ecc89d
Building Detox.framework from /Users/kristofer/Git/GitHub/StoDevX/AAO-React-Native/node_modules/detox/ios_src...
+ /Users/kristofer/Git/GitHub/StoDevX/AAO-React-Native/node_modules/detox/scripts/build_universal_framework.sh /Users/kristofer/Git/GitHub/StoDevX/AAO-React-Native/node_modules/detox/ios_src/Detox.xcodeproj /Users/kristofer/Library/Detox/ios/aba5c8f25bf328b40be1e29d2d653101f6ecc89d/DetoxBuild
child_process.js:621
    throw err;
    ^

Error: Command failed: /Users/kristofer/Git/GitHub/StoDevX/AAO-React-Native/node_modules/detox/scripts/build_framework.ios.sh
    at checkExecSyncError (child_process.js:600:11)
    at Object.execFileSync (child_process.js:618:13)
    at Object.<anonymous> (/Users/kristofer/Git/GitHub/StoDevX/AAO-React-Native/node_modules/detox/scripts/postinstall.js:2:27)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)


```

I'm suspicious of the line

>xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance.

Does this mean I can't successfully install dependencies now?  (Note: **I do not have XCode installed, nor will I. Just the command-line tools.**)

**Comment by rye** [comment]
Reported upstream at wix/detox#897.
