### ISSUE TITLE
All test suites are failing

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#6153]
Do we need to update our jest config? Did one of our upgrades cause our tests to break?  

I am seeing the following for all test suites:

```
Test suite failed to run

Jest encountered an unexpected token

Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

By default "node_modules" folder is ignored by transformers.

Here's what you can do:
• If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
• If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
• To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
• If you need a custom transformation specify a "transform" option in your config.
• If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

You'll find more details and examples of these config options in the docs:
https://jestjs.io/docs/configura

For information about custom transformations, see:
https://jestjs.io/docs/code-transforma

Details:

/home/runner/work/AAO-React-Native/AAO-React-Native/node_modules/@react-native/polyfills/error-guard.js:14
type ErrorHandler = (error: mixed, isFatal: boolean) => void;
     ^^^^^^^^^^^^
     
SyntaxError: Unexpected identifier

     at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1773:14)
     at Object.<anonymous> (node_modules/react-native/jest/setup.js:419:6)
```

**Comment by drewvolz** [comment]
I think part of this may be needing to exclude `@react-native` from the `transformIgnorePatterns`

```diff
"transformIgnorePatterns": [
- "node_modules/(?!(jest-)?react-native|glamorous-native|react-navigation)"
+ "node_modules/(?!(jest-)?react-native|@react-native|glamorous-native|react-navigation)"
],
```

Which then presents a different but less clear error. For example, running an isolated test...

```sh
yarn run jest source/views/menus/lib/__tests__/trim-names.test.ts
```

...results in the following: 

```
 Details:

    node_modules/@frogpond/titlecase/dist/index.js:9
    import { articles } from "./articles.js";
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    > 1 | import {toLaxTitleCase} from '@frogpond/titlecase'
        | ^
      2 |
      3 | export function trimStationName(stationName: string) {
      4 |       return stationName.replace(/<strong>@(.*)<\/strong>/u, '$1')
```

This one makes less sense to me because of how we've defined the `tsconfig`. What do we need to change in our module resolution strategy?

- https://www.typescriptlang.org/tsconfig#moduleResolution
- https://www.typescriptlang.org/docs/handbook/module-resolution.html

**Comment by drewvolz** [comment]
This may be complete as of:
- adding `@react-native` to `transformIgnorePatterns` via https://github.com/StoDevX/AAO-React-Native/pull/6292
- adding `@frogpond` to `transformIgnorePatterns` via https://github.com/StoDevX/AAO-React-Native/pull/6152/commits/1ff97cf3e106e98656ec88a2a071487f9b877e32
