### ISSUE TITLE
Android prelaunch report

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#6318]
Google play console has a few notes for us on the android app's stability:

First issue x10
```
FATAL EXCEPTION: create_react_context
Process: com.allaboutolaf, PID: 15051
java.lang.RuntimeException: Unable to load script. Make sure you're either running Metro (run 'npx react-native start') or that your bundle 'index.android.bundle' is packaged correctly for release.
	at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromAssets(Native Method)
	at com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromAssets(CatalystInstanceImpl.java:248)
	at com.facebook.react.bridge.JSBundleLoader$1.loadScript(JSBundleLoader.java:29)
	at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:277)
	at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1422)
	at com.facebook.react.ReactInstanceManager.access$1200(ReactInstanceManager.java:138)
	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1111)
	at java.lang.Thread.run(Thread.java:1012)
[ 08-17 01:43:48.192     0:    0 W/         ]
c7  14366 Partial cmo only supported with 1 segment
[ 08-17 01:43:48.192     0:    0 W/         ]
c7  14366 is dma_set_max_seg_size being set on dev:kgsl-3d0
[ 08-17 01:43:48.213     0:    0 W/         ]
c4  14366 Partial cmo only supported with 1 segment
[ 08-17 01:43:48.213     0:    0 W/         ]
c4  14366 is dma_set_max_seg_size being set on dev:kgsl-3d0
```

Second issue

```
Failed to finalize session : INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113
```

**Comment by drewvolz** [comment]
The PR downgrading gradle versions resolved 10 of the 11 issue instances (first issue).

The second issue "failed to finalize session" is still being reported in one instance.

**Comment by hawkrives** [comment]
Closing as we've removed Android support
